# Generated by Django 5.0.6 on 2024-05-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_line',
            field=models.CharField(max_length=10, verbose_name='Línea asignada'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sim_number',
            field=models.CharField(max_length=19, verbose_name='Número de SIM'),
        ),
    ]
