# Generated by Django 5.0.6 on 2024-05-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_profile'),
        ('users', '0008_profile_is_active'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devices_vehicle', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='device',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_profile', to='users.profile'),
        ),
    ]
