# Generated by Django 5.0.6 on 2024-05-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_vehicle_alter_device_profile'),
        ('vehicles', '0002_vehicle_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices_vehicle', to='vehicles.vehicle'),
        ),
    ]
