# Generated by Django 5.0.6 on 2024-05-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_device_vehicle'),
        ('users', '0008_profile_is_active'),
        ('vehicles', '0002_vehicle_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devices_profile', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='device',
            name='vehicle',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices_vehicle', to='vehicles.vehicle'),
        ),
    ]
