# Generated by Django 5.0.6 on 2024-06-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_alter_device_vehicle'),
        ('users', '0011_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_profile', to='users.profile'),
        ),
    ]
