# Generated by Django 5.0.6 on 2024-06-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_device_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(choices=[('Cellocator', 'Cellocator')], default='JIMI', max_length=50, verbose_name='Marca del dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default='01020300', max_length=15, verbose_name='Identificador del dispositivo'),
        ),
    ]
