# Generated by Django 5.0.6 on 2024-05-20 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador único')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca del vehículo')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo del vehículo')),
                ('year', models.PositiveIntegerField(verbose_name='Año del vehículo')),
                ('color', models.CharField(max_length=50, verbose_name='Color del vehículo')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Número de serie/VIN del vehículo')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa del vehículo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
