# Generated by Django 5.0.6 on 2024-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='display_name',
            field=models.CharField(default='Vehículo', max_length=50, verbose_name='Nombre del vehículo'),
        ),
    ]
