# Generated by Django 5.0.6 on 2024-05-17 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_changed_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador único')),
                ('names', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('pattern_last_name', models.CharField(max_length=150, verbose_name='Apellido paterno')),
                ('mattern_last_name', models.CharField(max_length=150, verbose_name='Apellido materno')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono celular')),
                ('is_owner', models.BooleanField(default=False, verbose_name='¿El titular de la cuenta puede reportar siniestros?')),
                ('adress', models.CharField(max_length=150, verbose_name='Dirección')),
                ('ext_number', models.CharField(max_length=10, verbose_name='Número exterior')),
                ('int_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número interior')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Código postal')),
                ('state', models.CharField(max_length=150, verbose_name='Estado')),
                ('city', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('colony', models.CharField(max_length=150, verbose_name='Colonia')),
                ('adress_type', models.CharField(choices=[('D', 'Domicilio particular'), ('O', 'Oficina')], default='D', max_length=1, verbose_name='Tipo de dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['created_at'],
            },
        ),
    ]
