# Generated by Django 5.0.6 on 2024-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='default', max_length=150, verbose_name='Nombre de perfil'),
        ),
    ]
