# Generated by Django 5.0.6 on 2024-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_device',
            field=models.BooleanField(default=False, verbose_name='Dispositivo creado'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_emergency_contact',
            field=models.BooleanField(default=False, verbose_name='Contacto de emergencia creado'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_profile',
            field=models.BooleanField(default=False, verbose_name='Perfil creado'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_vehicle',
            field=models.BooleanField(default=False, verbose_name='Vehículo creado'),
        ),
    ]
