# Generated by Django 5.0.6 on 2024-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_create_device_user_create_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de perfil'),
        ),
    ]
